#!/usr/bin/env bash
set -euo pipefail
echo "Nooting up! 🐧"

mkdir -p ~/.config/kitty
cp kitty.conf ~/.config/kitty/kitty.conf
echo "Found kitty 🐈‍ Nya~"

mkdir -p ~/.config/topgrade
cp topgrade.toml ~/.config/topgrade/topgrade.toml
echo "Glasses topped! 🥂"

cp gitconfig ~/.gitconfig
echo "Git got 🤓"

cp zshrc ~/.zshrc
echo "Beautified commandline 💅"

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
echo "Oh my 😏"
